export const SideBarLinks = [
  {
    id: 1,
    name: "Dashboard",
    path: "/admin/dashboard",
    active: true,
    tablename: "",
    order: 1,
    header: [],
  },
  {
    id: 2,
    name: "Admission Form",
    path: "/admin/forms/admission",
    active: true,
    tablename: "admissionform",
    order: 2,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "Name", field: "name" },
      { headerName: "Email", field: "email" },
      { headerName: "Mobile", field: "mobile" },
      { headerName: "Address", field: "address" },
      { headerName: "Date of Birth", field: "date_of_birth" },
      { headerName: "Standard Class", field: "standard_class" },
      { headerName: "Place", field: "place" },
      { headerName: "School Name", field: "school_name" },
      { headerName: "Message", field: "message" },
      { headerName: "Create Date", field: "created_at" },
    ],
  },
  {
    id: 3,
    name: "Alumniclub Form",
    path: "/admin/forms/alumniclub",
    active: true,
    tablename: "alumniclubform",
    order: 3,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "Name", field: "name" },
      { headerName: "Last Name", field: "last_name" },
      { headerName: "Email", field: "email" },
      { headerName: "Mobile", field: "mobile" },
      { headerName: "Address", field: "address" },
      { headerName: "Date of Birth", field: "date_of_birth" },
      { headerName: "Standard Class", field: "standard_class" },
      { headerName: "Batch", field: "batch" },
      { headerName: "Gender", field: "gender" },
      { headerName: "Marital Status", field: "marital_status" },
      { headerName: "Last Year School", field: "last_year_school" },
      { headerName: "Create Date", field: "created_at" },
    ],
  },
  {
    id: 4,
    name: "Career Form",
    path: "/admin/forms/career",
    active: true,
    tablename: "careerform",
    order: 4,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "Name", field: "name" },
      { headerName: "Email", field: "email" },
      { headerName: "Mobile", field: "mobile" },
      { headerName: "Branch", field: "branch" },
      { headerName: "Position", field: "position" },
      { headerName: "Resume", field: "resume" },
      { headerName: "Create Date", field: "created_at" },
    ],
  },
  {
    id: 5,
    name: "Contact Form",
    path: "/admin/forms/contact",
    active: true,
    tablename: "contactform",
    order: 5,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "Name", field: "name" },
      { headerName: "Email", field: "email" },
      { headerName: "Mobile", field: "mobile" },
      { headerName: "Message", field: "message" },
      { headerName: "Profile", field: "profile" },
      { headerName: "Create Date", field: "created_at" },
    ],
  },
  {
    id: 6,
    name: "Reach Us Form",
    path: "/admin/forms/reachus",
    active: true,
    tablename: "reachusform",
    order: 6,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "Name", field: "name" },
      { headerName: "Email", field: "email" },
      { headerName: "Mobile", field: "mobile" },
      { headerName: "Message", field: "message" },
      { headerName: "Branch", field: "branch" },
      { headerName: "Create Date", field: "created_at" },
    ],
  },
  {
    id: 7,
    name: "Profile",
    path: "/admin/profile",
    active: false,
    tablename: "users",
    order: 7,
    header: [
      { headerName: "Id", field: "id" },
      { headerName: "User Name", field: "username" },
      { headerName: "Email", field: "email" },
    ],
  },
];
